### PR TITLE
Pr fix1

### PR DESCRIPTION
**Pull request by poblin-orange**
Hello,
this is a base PR to fix internet dependency. As bosh blobs cant be PR, i submit the fix before creating final bosh release on our fork.
To align blobs, must use bosh-gen extract-pkg ../bosh/packages/nginx so u can copy the nginx blobs, then sync them on the cloudfoundry-community/nginx  s3 bucket

### CODE REVIEW

**Comment by cunnie** [comment]
Thank you Pierre, I am going to merge your pull request and test it on my deployment.

I am curious why you decided to go with a back level version of nginx (version 1.6.2 -> 1.4.5). Did 1.6.2 pose difficulty?

Thanks,

**Comment by cunnie** [comment]
My attempt at deploying the new release failed, @poblin-orange . I'm not sure why it failed—can see what went wrong?

```
Command 'deploy' failed:
  Deploying:
    Building state for instance 'nginx_ntp_xip/0':
      Compiling job package dependencies for instance 'nginx_ntp_xip/0':
        Compiling job package dependencies:
          Remotely compiling package 'nginx' with the agent:
            Sending 'compile_package' to the agent:
              Sending 'get_task' to the agent:
                Agent responded with error: Action Failed get_task: Task 36c9459e-8a33-40e5-56c8-b3014807bec7 result: Compiling package nginx: Running packaging script: Command exited with 1; Truncated stdout: 
```

The important piece seems to be the following:

```
adding module in ../nginx-upload-module-2.2
./configure: error: no ../nginx-upload-module-2.2/config was found
, Stderr: + echo 'Extracting pcre...'
```

The gist is [here](https://gist.github.com/cunnie/77496aa909e3548e7688)

The `bosh-gen` command didn't seem to help with the blobs, so I had to find them on the Internet and download them and rename them:

```
 2015-10-21 16:09:03 ☆ ruby 2.2.3p173 tara in ~/workspace/nginx-release
± bc |master ✓| → bosh-gen extract-pkg packages/nginx/
       exist  packages/nginx
   identical  packages/nginx/packaging
   identical  packages/nginx/spec
   identical  packages/nginx/spec.yml
```

Thanks,

**Comment by cunnie** [comment]
It seems like there are slight inconsistencies in the files I downloaded on the Internet from the files you found.

Perhaps the next pull request you could add a list of links where you downloaded the .tar.gz files from. Finding them on my own hasn't worked, and `bosh-gen extract` didn't seem to extract them properly.

**Comment by cunnie** [comment]
Pierre, I'm so sorry, but I think I have to revert your commit. It appears that your pull request brings in a library (`nginx_upload_module-2.2.0`) that was [abandoned](https://github.com/wmark/ossdl-overlay/issues/7) by its owner over 2 years ago! I think that's the source of many of my difficulties.

From the forum it appears that the library offers value to mobile clients; perhaps a good solution would be to have two versions of the nginx release—yours, with an older version of nginx and the troubled library, and this one. Let me know what you think.

**Comment by poblin-orange** [comment]
Hello Brian.
in fact i just relied on original bosh bosh-release to reuse their bundle artifact. One important point before using bosh-gen extract-pkg ../bosh/packages is that u must have synced the blob in the original bosh release. When blobs are synced in original, bosh-gen copies also the blobs to the local release, enabling you to sync in your own release bucket.

As it is a straight reuse, i didnt notice the nginx version, and module which might be outdated ...

@cppforlife, any specific reason to use nginx 1.4 and this specific module in bosh? 

I think we could align, with a clean nginx-release, reusable in big releases like bosh, or cloudfoundry, as its very common use case.
Also would avoid cluttering the S3 community blobstore with single component copied in multilple blob.

**Pull request merged**
