### PR TITLE
Adding extra drain and post-start scripts into the lifecycle process

### PR DESCRIPTION
**Pull request by jdesulme**
We have use case of where we want to run an install script for monitoring that occurs after nginx itself has started. In addition a placeholder for draining so that we can implement custom scripts that deregisters the nginx for a given load balancer without interruption to the end user. We've done already in other releases through the drain script but would like to augment this one so we can just add  it.

### CODE REVIEW

**Comment by cunnie** [comment]
@jdesulme : I like it! Thank you.

Could you modify the commit message to include your use case? I like commit messages that provide rationale, and you've already provided a good one. Something along the following:

```
`nginx` job includes drain and post-start scripts 

This satisfies the use case of where one wants to run an install script for monitoring that occurs after nginx itself has started. In addition, one can use the drain script to implement custom scripts that deregister the nginx server from a given load balancer without interruption to the end user.
```

**Comment by jdesulme** [comment]
Hey @cunnie thanks for the quick feedback. I have updated the commit message to reflect the new entry. 

In addition I was wondering when do you plan on releasing the next version of this that includes the latest mainline branch release.

**Comment by cunnie** [comment]
@jdesulme 

> I was wondering when do you plan on releasing the next version of this that includes the latest mainline branch release.

Soon because 1.14.0 was recently released, but no promises.

**Comment by cunnie** [comment]
@jdesulme thanks again for the PR. I had to amend the default drain script, it didn't work ([it needed to print the number 0 to stdout as well as exit 0](https://bosh.io/docs/drain/)). It bombed out with the following:

```
Task 16 | 00:45:25 | Deleting instances: nginx/a9607238-09b8-4b10-bf37-48d05326c553 (0) (00:00:01)
                   L Error: Action Failed get_task: Task 977a1c5a-2ce1-46f0-41ea-4fa057b1879d result: 1 of 1 drain scripts failed. Failed Jobs: nginx.
```

Also, there was some trailing whitespace on two lines, and a spelling error (fixed). Other than that the PR seems to work well.

**Comment by jdesulme** [comment]
Hey @cunnie  - Thanks for merging my pull request. As for the drain script initially failing that was a mistake on my part in that I didn't pull in my test code with it. Anyhow I do appreciate you pushing out a new release so quickly that includes it! 😀

**Pull request merged**
